---
- name: Install Emacs
  homebrew: name=emacs state=present install_options=cocoa,without-x
  register: emacs_install

- name: Link Emacs
  shell: ln -s $( brew --prefix emacs )/Emacs.app /Applications
  when: emacs_install|changed
