---
- name: Install Go
  homebrew: name=go state=present install_options=cross-compile-common

- name: Check Go Commands
  stat: path={{ home_dir }}/.go/bin/{{ item | basename }}
  with_items: go_applications
  register: go_cmd_installed

- name: Install Go Commands
  shell: GOPATH={{ home_dir }}/.go go get {{ item }}
  with_items: go_applications
  when: "item in go_cmd_installed.results|selectattr('stat.exists','sameas',false)|map(attribute='item')"

- name: Check cli-init
  stat: path={{ home_dir }}/.go/bin/cli-init
  register: go_cli_init_installed

- name: Install cli-init
  shell: GOPATH={{ home_dir }}/.go bash -c 'go get -d github.com/tcnksm/cli-init && cd $GOPATH/src/github.com/tcnksm/cli-init && make install'
  when: go_cli_init_installed.stat.exists == false
